// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpIdentityProg.Data;

#nullable disable

namespace SharpIdentityProg.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240122080215_Identity_Initial")]
    partial class Identity_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");
#pragma warning restore 612, 618
        }
    }
}
