// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SharpCountriesProg.Models;

#nullable disable

namespace SharpCountriesProg.Migrations
{
    [DbContext(typeof(CountriesDbContext))]
    [Migration("20240122073601_Countries_CreateTables")]
    partial class Countries_CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharpCountriesProg.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<double>("PopulationMln")
                        .HasColumnType("float");

                    b.Property<string>("President")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("SurfaceAreaKm2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
