// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpCountriesProg.Models;

#nullable disable

namespace SharpCountriesProg.Migrations
{
    [DbContext(typeof(CountriesDbContext))]
    [Migration("20240122104436_Countries_SeedData")]
    partial class Countries_SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharpCountriesProg.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PopulationMln")
                        .HasColumnType("real");

                    b.Property<string>("President")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurfaceAreaKm2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Capital = "Kabul",
                            Currency = "Afghani",
                            Name = "Afghanistan",
                            PopulationMln = 38f,
                            President = "Ashraf Ghani",
                            SurfaceAreaKm2 = 652230
                        },
                        new
                        {
                            Id = "2",
                            Capital = "Tirana (Tirane)",
                            Currency = "Lek",
                            Name = "Albania",
                            PopulationMln = 2.87f,
                            President = "Ilir Meta",
                            SurfaceAreaKm2 = 28748
                        },
                        new
                        {
                            Id = "3",
                            Capital = "Algiers",
                            Currency = "Algerian Dinar",
                            Name = "Algeria",
                            PopulationMln = 44.6f,
                            President = "Abdelmadjid Tebboune",
                            SurfaceAreaKm2 = 2381741
                        },
                        new
                        {
                            Id = "4",
                            Capital = "Andorra la Vella",
                            Currency = "Euro",
                            Name = "Andorra",
                            PopulationMln = 0.08f,
                            President = "Joan Enric Vives SicÃ­lia",
                            SurfaceAreaKm2 = 468
                        },
                        new
                        {
                            Id = "5",
                            Capital = "Luanda",
                            Currency = "Angolan Kwanza",
                            Name = "Angola",
                            PopulationMln = 32.9f,
                            President = "JoÃ£o LourenÃ§o",
                            SurfaceAreaKm2 = 1246700
                        },
                        new
                        {
                            Id = "6",
                            Capital = "Saint John's",
                            Currency = "East Caribbean Dollar",
                            Name = "Antigua and Barbuda",
                            PopulationMln = 0.1f,
                            President = "Gaston Browne",
                            SurfaceAreaKm2 = 442
                        },
                        new
                        {
                            Id = "7",
                            Capital = "Buenos Aires",
                            Currency = "Argentine Peso",
                            Name = "Argentina",
                            PopulationMln = 45.4f,
                            President = "Alberto FernÃ¡ndez",
                            SurfaceAreaKm2 = 2780400
                        },
                        new
                        {
                            Id = "8",
                            Capital = "Yerevan",
                            Currency = "Armenian Dram",
                            Name = "Armenia",
                            PopulationMln = 2.96f,
                            President = "Armen Sarkissian",
                            SurfaceAreaKm2 = 29743
                        },
                        new
                        {
                            Id = "9",
                            Capital = "Canberra",
                            Currency = "Australian Dollar",
                            Name = "Australia",
                            PopulationMln = 25.9f,
                            President = "Scott Morrison",
                            SurfaceAreaKm2 = 7692024
                        },
                        new
                        {
                            Id = "10",
                            Capital = "Vienna",
                            Currency = "Euro",
                            Name = "Austria",
                            PopulationMln = 8.9f,
                            President = "Alexander Van der Bellen",
                            SurfaceAreaKm2 = 83879
                        },
                        new
                        {
                            Id = "11",
                            Capital = "Baku",
                            Currency = "Azerbaijani Manat",
                            Name = "Azerbaijan",
                            PopulationMln = 10.2f,
                            President = "Ilham Aliyev",
                            SurfaceAreaKm2 = 86600
                        },
                        new
                        {
                            Id = "12",
                            Capital = "Nassau",
                            Currency = "Bahamian Dollar",
                            Name = "Bahamas",
                            PopulationMln = 0.39f,
                            President = "Hubert Minnis",
                            SurfaceAreaKm2 = 13880
                        },
                        new
                        {
                            Id = "13",
                            Capital = "Manama",
                            Currency = "Bahraini Dinar",
                            Name = "Bahrain",
                            PopulationMln = 1.7f,
                            President = "Hamad bin Isa Al Khalifa",
                            SurfaceAreaKm2 = 760
                        },
                        new
                        {
                            Id = "14",
                            Capital = "Dhaka",
                            Currency = "Bangladeshi Taka",
                            Name = "Bangladesh",
                            PopulationMln = 165.7f,
                            President = "Abdul Hamid",
                            SurfaceAreaKm2 = 147570
                        },
                        new
                        {
                            Id = "15",
                            Capital = "Bridgetown",
                            Currency = "Barbadian Dollar",
                            Name = "Barbados",
                            PopulationMln = 0.29f,
                            President = "Mia Mottley",
                            SurfaceAreaKm2 = 430
                        },
                        new
                        {
                            Id = "16",
                            Capital = "Minsk",
                            Currency = "Belarusian Ruble",
                            Name = "Belarus",
                            PopulationMln = 9.4f,
                            President = "Alyaksandr Lukashenka",
                            SurfaceAreaKm2 = 207600
                        },
                        new
                        {
                            Id = "17",
                            Capital = "Brussels",
                            Currency = "Euro",
                            Name = "Belgium",
                            PopulationMln = 11.5f,
                            President = "Alexander De Croo",
                            SurfaceAreaKm2 = 30528
                        },
                        new
                        {
                            Id = "18",
                            Capital = "Belmopan",
                            Currency = "Belize Dollar",
                            Name = "Belize",
                            PopulationMln = 0.4f,
                            President = "Johnny BriceÃ±o",
                            SurfaceAreaKm2 = 22966
                        },
                        new
                        {
                            Id = "19",
                            Capital = "Porto Novo",
                            Currency = "West African CFA franc",
                            Name = "Benin",
                            PopulationMln = 12.1f,
                            President = "Patrice Talon",
                            SurfaceAreaKm2 = 112622
                        },
                        new
                        {
                            Id = "20",
                            Capital = "Thimphu",
                            Currency = "Bhutanese Ngultrum",
                            Name = "Bhutan",
                            PopulationMln = 0.8f,
                            President = "Jigme Khesar Namgyel Wangchuck",
                            SurfaceAreaKm2 = 38394
                        },
                        new
                        {
                            Id = "21",
                            Capital = "La Paz",
                            Currency = "Boliviano",
                            Name = "Bolivia",
                            PopulationMln = 11.4f,
                            President = "Luis Arce",
                            SurfaceAreaKm2 = 1098581
                        },
                        new
                        {
                            Id = "22",
                            Capital = "Sarajevo",
                            Currency = "Bosnia and Herzegovina Convertible Mark",
                            Name = "Bosnia and Herzegovina",
                            PopulationMln = 3.3f,
                            President = "Å efik DÅ¾aferoviÄ‡",
                            SurfaceAreaKm2 = 51197
                        },
                        new
                        {
                            Id = "23",
                            Capital = "Gaborone",
                            Currency = "Botswana Pula",
                            Name = "Botswana",
                            PopulationMln = 2.4f,
                            President = "Mokgweetsi Masisi",
                            SurfaceAreaKm2 = 581730
                        },
                        new
                        {
                            Id = "24",
                            Capital = "Brasilia",
                            Currency = "Brazilian Real",
                            Name = "Brazil",
                            PopulationMln = 212.6f,
                            President = "Jair Bolsonaro",
                            SurfaceAreaKm2 = 8515767
                        },
                        new
                        {
                            Id = "25",
                            Capital = "Bandar Seri Begawan",
                            Currency = "Brunei Dollar",
                            Name = "Brunei",
                            PopulationMln = 0.4f,
                            President = "Hassanal Bolkiah",
                            SurfaceAreaKm2 = 5765
                        },
                        new
                        {
                            Id = "26",
                            Capital = "Sofia",
                            Currency = "Bulgarian Lev",
                            Name = "Bulgaria",
                            PopulationMln = 6.9f,
                            President = "Rumen Radev",
                            SurfaceAreaKm2 = 110879
                        },
                        new
                        {
                            Id = "27",
                            Capital = "Ouagadougou",
                            Currency = "West African CFA franc",
                            Name = "Burkina Faso",
                            PopulationMln = 20.3f,
                            President = "Roch Marc Christian KaborÃ©",
                            SurfaceAreaKm2 = 274200
                        },
                        new
                        {
                            Id = "28",
                            Capital = "Gitega",
                            Currency = "Burundian Franc",
                            Name = "Burundi",
                            PopulationMln = 11.5f,
                            President = "Evariste Ndayishimiye",
                            SurfaceAreaKm2 = 27834
                        },
                        new
                        {
                            Id = "29",
                            Capital = "Phnom Penh",
                            Currency = "Cambodian Riel",
                            Name = "Cambodia",
                            PopulationMln = 16.5f,
                            President = "King Norodom Sihamoni",
                            SurfaceAreaKm2 = 181035
                        },
                        new
                        {
                            Id = "30",
                            Capital = "Yaounde",
                            Currency = "Central African CFA franc",
                            Name = "Cameroon",
                            PopulationMln = 26.5f,
                            President = "Paul Biya",
                            SurfaceAreaKm2 = 475442
                        },
                        new
                        {
                            Id = "31",
                            Capital = "Ottawa",
                            Currency = "Canadian Dollar",
                            Name = "Canada",
                            PopulationMln = 38.4f,
                            President = "Justin Trudeau",
                            SurfaceAreaKm2 = 9976140
                        },
                        new
                        {
                            Id = "32",
                            Capital = "Praia",
                            Currency = "Cape Verdean Escudo",
                            Name = "Cape Verde",
                            PopulationMln = 0.5f,
                            President = "Jorge Carlos Fonseca",
                            SurfaceAreaKm2 = 4033
                        },
                        new
                        {
                            Id = "33",
                            Capital = "Bangui",
                            Currency = "Central African CFA franc",
                            Name = "Central African Republic",
                            PopulationMln = 4.7f,
                            President = "Catherine Samba-Panza",
                            SurfaceAreaKm2 = 622984
                        },
                        new
                        {
                            Id = "34",
                            Capital = "N'Djamena",
                            Currency = " Central African CFA franc",
                            Name = "Chad",
                            PopulationMln = 16.4f,
                            President = "Idriss DÃ©by",
                            SurfaceAreaKm2 = 1284000
                        },
                        new
                        {
                            Id = "35",
                            Capital = "Santiago",
                            Currency = "Chilean Peso",
                            Name = "Chile",
                            PopulationMln = 19.2f,
                            President = "SebastiÃ¡n PiÃ±era",
                            SurfaceAreaKm2 = 756102
                        },
                        new
                        {
                            Id = "36",
                            Capital = "Beijing",
                            Currency = "Chinese Yuan",
                            Name = "China",
                            PopulationMln = 1444f,
                            President = "Xi Jinping",
                            SurfaceAreaKm2 = 9596960
                        },
                        new
                        {
                            Id = "37",
                            Capital = "Bogota",
                            Currency = "Colombian Peso",
                            Name = "Colombia",
                            PopulationMln = 50.9f,
                            President = "IvÃ¡n Duque",
                            SurfaceAreaKm2 = 1141748
                        },
                        new
                        {
                            Id = "38",
                            Capital = "Moroni",
                            Currency = "Comorian Franc",
                            Name = "Comoros",
                            PopulationMln = 0.9f,
                            President = "Azali Assoumani",
                            SurfaceAreaKm2 = 1861
                        },
                        new
                        {
                            Id = "39",
                            Capital = "San Jose",
                            Currency = "Costa Rican ColÃ³n",
                            Name = "Costa Rica",
                            PopulationMln = 5.1f,
                            President = "Carlos Alvarado Quesada",
                            SurfaceAreaKm2 = 51100
                        },
                        new
                        {
                            Id = "40",
                            Capital = "Zagreb",
                            Currency = "Croatian Kuna",
                            Name = "Croatia",
                            PopulationMln = 4.1f,
                            President = "Zoran MilanoviÄ‡",
                            SurfaceAreaKm2 = 56594
                        },
                        new
                        {
                            Id = "41",
                            Capital = "Havana",
                            Currency = "Cuban Peso",
                            Name = "Cuba",
                            PopulationMln = 11.2f,
                            President = "Miguel DÃ­az-Canel",
                            SurfaceAreaKm2 = 109884
                        },
                        new
                        {
                            Id = "42",
                            Capital = "Nicosia",
                            Currency = "Euro",
                            Name = "Cyprus",
                            PopulationMln = 1.2f,
                            President = "Nicos Anastasiades",
                            SurfaceAreaKm2 = 9251
                        },
                        new
                        {
                            Id = "43",
                            Capital = "Prague",
                            Currency = "Czech Koruna",
                            Name = "Czech Republic (Czechia)",
                            PopulationMln = 10.7f,
                            President = "MiloÅ¡ Zeman",
                            SurfaceAreaKm2 = 78867
                        },
                        new
                        {
                            Id = "44",
                            Capital = "Copenhagen",
                            Currency = "Danish Krone",
                            Name = "Denmark",
                            PopulationMln = 5.8f,
                            President = "Mette Frederiksen",
                            SurfaceAreaKm2 = 42433
                        },
                        new
                        {
                            Id = "45",
                            Capital = "Djibouti",
                            Currency = "Djiboutian Franc",
                            Name = "Djibouti",
                            PopulationMln = 1f,
                            President = "Ismail Omar Guelleh",
                            SurfaceAreaKm2 = 23000
                        },
                        new
                        {
                            Id = "46",
                            Capital = "Roseau",
                            Currency = "East Caribbean Dollar",
                            Name = "Dominica",
                            PopulationMln = 0.1f,
                            President = "Charles Savarin",
                            SurfaceAreaKm2 = 751
                        },
                        new
                        {
                            Id = "47",
                            Capital = "Santo Domingo",
                            Currency = "Dominican Peso",
                            Name = "Dominican Republic",
                            PopulationMln = 10.8f,
                            President = "Luis Abinader",
                            SurfaceAreaKm2 = 48671
                        },
                        new
                        {
                            Id = "48",
                            Capital = "Dili",
                            Currency = "United States Dollar",
                            Name = "East Timor",
                            PopulationMln = 1.3f,
                            President = "Francisco Guterres",
                            SurfaceAreaKm2 = 14874
                        },
                        new
                        {
                            Id = "49",
                            Capital = "Quito",
                            Currency = "United States Dollar",
                            Name = "Ecuador",
                            PopulationMln = 17.1f,
                            President = "LenÃ­n Moreno",
                            SurfaceAreaKm2 = 276841
                        },
                        new
                        {
                            Id = "50",
                            Capital = "Cairo",
                            Currency = "Egyptian Pound",
                            Name = "Egypt",
                            PopulationMln = 101.7f,
                            President = "Abdel Fattah el-Sisi",
                            SurfaceAreaKm2 = 1002450
                        },
                        new
                        {
                            Id = "51",
                            Capital = "San Salvador",
                            Currency = "United States Dollar",
                            Name = "El Salvador",
                            PopulationMln = 6.5f,
                            President = "Nayib Bukele",
                            SurfaceAreaKm2 = 21041
                        },
                        new
                        {
                            Id = "52",
                            Capital = "London",
                            Currency = "British Pound",
                            Name = "England",
                            PopulationMln = 56.3f,
                            President = "Queen Elizabeth II",
                            SurfaceAreaKm2 = 130395
                        },
                        new
                        {
                            Id = "53",
                            Capital = "Malabo",
                            Currency = " Central African CFA franc",
                            Name = "Equatorial Guinea",
                            PopulationMln = 1.4f,
                            President = "Teodoro Obiang Nguema Mbasogo",
                            SurfaceAreaKm2 = 28051
                        },
                        new
                        {
                            Id = "54",
                            Capital = "Asmara",
                            Currency = "Eritrean Nakfa",
                            Name = "Eritrea",
                            PopulationMln = 3.6f,
                            President = "Isaias Afwerki",
                            SurfaceAreaKm2 = 117600
                        },
                        new
                        {
                            Id = "55",
                            Capital = "Tallinn",
                            Currency = "Euro",
                            Name = "Estonia",
                            PopulationMln = 1.3f,
                            President = "Kersti Kaljulaid",
                            SurfaceAreaKm2 = 45339
                        },
                        new
                        {
                            Id = "56",
                            Capital = "Mbabane",
                            Currency = "Lilangeni",
                            Name = "Eswatini (Swaziland)",
                            PopulationMln = 1.1f,
                            President = "Mswati III",
                            SurfaceAreaKm2 = 17364
                        },
                        new
                        {
                            Id = "57",
                            Capital = "Addis Ababa",
                            Currency = "Ethiopian Birr",
                            Name = "Ethiopia",
                            PopulationMln = 118.4f,
                            President = "Sahle-Work Zewde",
                            SurfaceAreaKm2 = 1104300
                        },
                        new
                        {
                            Id = "58",
                            Capital = "Palikir",
                            Currency = "United States Dollar",
                            Name = "Federated States of Micronesia",
                            PopulationMln = 0.1f,
                            President = "David W. Panuelo",
                            SurfaceAreaKm2 = 702
                        },
                        new
                        {
                            Id = "59",
                            Capital = "Suva",
                            Currency = "Fijian Dollar",
                            Name = "Fiji",
                            PopulationMln = 0.9f,
                            President = "Jioji Konrote",
                            SurfaceAreaKm2 = 18274
                        },
                        new
                        {
                            Id = "60",
                            Capital = "Helsinki",
                            Currency = "Euro",
                            Name = "Finland",
                            PopulationMln = 5.5f,
                            President = "Sauli Vainamo NiinistÃ",
                            SurfaceAreaKm2 = 338145
                        },
                        new
                        {
                            Id = "61",
                            Capital = "Paris",
                            Currency = "Euro",
                            Name = "France",
                            PopulationMln = 67.1f,
                            President = "Emmanuel Macron",
                            SurfaceAreaKm2 = 551695
                        },
                        new
                        {
                            Id = "62",
                            Capital = "Libreville",
                            Currency = "Central African CFA franc",
                            Name = "Gabon",
                            PopulationMln = 2.2f,
                            President = "Ali Bongo Ondimba",
                            SurfaceAreaKm2 = 267667
                        },
                        new
                        {
                            Id = "63",
                            Capital = "Banjul",
                            Currency = "Gambian Dalasi",
                            Name = "Gambia",
                            PopulationMln = 2.4f,
                            President = "Adama Barrow",
                            SurfaceAreaKm2 = 10689
                        },
                        new
                        {
                            Id = "64",
                            Capital = "Tbilisi",
                            Currency = "Georgian Lari",
                            Name = "Georgia",
                            PopulationMln = 3.7f,
                            President = "Salome Zurabishvili",
                            SurfaceAreaKm2 = 69700
                        },
                        new
                        {
                            Id = "65",
                            Capital = "Berlin",
                            Currency = "Euro",
                            Name = "Germany",
                            PopulationMln = 83.2f,
                            President = "Frank-Walter Steinmeier",
                            SurfaceAreaKm2 = 357022
                        },
                        new
                        {
                            Id = "66",
                            Capital = "Accra",
                            Currency = "Ghanaian Cedi",
                            Name = "Ghana",
                            PopulationMln = 31.4f,
                            President = "Nana Akufo-Addo",
                            SurfaceAreaKm2 = 238535
                        },
                        new
                        {
                            Id = "67",
                            Capital = "Athens",
                            Currency = "Euro",
                            Name = "Greece",
                            PopulationMln = 10.4f,
                            President = "Katerina Sakellaropoulou",
                            SurfaceAreaKm2 = 131957
                        },
                        new
                        {
                            Id = "68",
                            Capital = "Saint George's",
                            Currency = "East Caribbean Dollar",
                            Name = "Grenada",
                            PopulationMln = 0.1f,
                            President = "Charles Angelo Savarin",
                            SurfaceAreaKm2 = 344
                        },
                        new
                        {
                            Id = "69",
                            Capital = "Guate mala City",
                            Currency = "Guatemalan Quetzal",
                            Name = "Guatemala",
                            PopulationMln = 17.8f,
                            President = "Alejandro Giammattei",
                            SurfaceAreaKm2 = 108889
                        },
                        new
                        {
                            Id = "70",
                            Capital = "Conakry",
                            Currency = "Guinean Franc",
                            Name = "Guinea",
                            PopulationMln = 12.4f,
                            President = "Alpha CondÃ©",
                            SurfaceAreaKm2 = 245857
                        },
                        new
                        {
                            Id = "71",
                            Capital = "Bissau",
                            Currency = "West African CFA franc",
                            Name = "Guinea-Bissau",
                            PopulationMln = 2f,
                            President = "Umaro Sissoco EmbalÃ³",
                            SurfaceAreaKm2 = 36125
                        },
                        new
                        {
                            Id = "72",
                            Capital = "Georgetown",
                            Currency = "Guyanese Dollar",
                            Name = "Guyana",
                            PopulationMln = 0.8f,
                            President = "irfaan Ali",
                            SurfaceAreaKm2 = 214969
                        },
                        new
                        {
                            Id = "73",
                            Capital = "Port-au-Prince",
                            Currency = "Haitian Gourde",
                            Name = "Haiti",
                            PopulationMln = 11.4f,
                            President = "Jovenel MoÃ¯se",
                            SurfaceAreaKm2 = 27750
                        },
                        new
                        {
                            Id = "74",
                            Capital = "Tegucigalpa",
                            Currency = "Honduran Lempira",
                            Name = "Honduras",
                            PopulationMln = 10.2f,
                            President = "Juan Orlando HernÃ¡ndez",
                            SurfaceAreaKm2 = 112492
                        },
                        new
                        {
                            Id = "75",
                            Capital = "Budapest",
                            Currency = "Hungarian Forint",
                            Name = "Hungary",
                            PopulationMln = 9.7f,
                            President = "JÃ¡nos Ãder",
                            SurfaceAreaKm2 = 93028
                        },
                        new
                        {
                            Id = "76",
                            Capital = "Reykjavik",
                            Currency = "Icelandic KrÃ³na",
                            Name = "Iceland",
                            PopulationMln = 0.4f,
                            President = "Gudni Thorlacius Johannesson",
                            SurfaceAreaKm2 = 103000
                        },
                        new
                        {
                            Id = "77",
                            Capital = "New Delhi",
                            Currency = "Indian Rupee",
                            Name = "India",
                            PopulationMln = 1393f,
                            President = "Ram Nath Kovind",
                            SurfaceAreaKm2 = 3287263
                        },
                        new
                        {
                            Id = "78",
                            Capital = "Jakarta",
                            Currency = "Indonesian Rupiah",
                            Name = "Indonesia",
                            PopulationMln = 276.4f,
                            President = "Joko Widodo",
                            SurfaceAreaKm2 = 1904569
                        },
                        new
                        {
                            Id = "79",
                            Capital = "Tehran",
                            Currency = "Iranian Rial",
                            Name = "Iran",
                            PopulationMln = 83.9f,
                            President = "Hassan Rouhani",
                            SurfaceAreaKm2 = 1648195
                        },
                        new
                        {
                            Id = "80",
                            Capital = "Baghdad",
                            Currency = "Iraqi Dinar",
                            Name = "Iraq",
                            PopulationMln = 39.3f,
                            President = "Barham Salih",
                            SurfaceAreaKm2 = 438317
                        },
                        new
                        {
                            Id = "81",
                            Capital = "Dublin",
                            Currency = "Euro",
                            Name = "Ireland",
                            PopulationMln = 4.9f,
                            President = "Michael D. Higgins",
                            SurfaceAreaKm2 = 70273
                        },
                        new
                        {
                            Id = "82",
                            Capital = "Jerusalem",
                            Currency = "Israeli New Shekel",
                            Name = "Israel",
                            PopulationMln = 9.2f,
                            President = "Reuven Rivlin",
                            SurfaceAreaKm2 = 20770
                        },
                        new
                        {
                            Id = "83",
                            Capital = "Rome",
                            Currency = "Euro",
                            Name = "Italy",
                            PopulationMln = 60.3f,
                            President = "Sergio Mattarella",
                            SurfaceAreaKm2 = 301340
                        },
                        new
                        {
                            Id = "84",
                            Capital = "Kingston",
                            Currency = "Jamaican Dollar",
                            Name = "Jamaica",
                            PopulationMln = 2.9f,
                            President = "Andrew Holness",
                            SurfaceAreaKm2 = 10991
                        },
                        new
                        {
                            Id = "85",
                            Capital = "Tokyo",
                            Currency = "Japanese Yen",
                            Name = "Japan",
                            PopulationMln = 126f,
                            President = "Naruhito",
                            SurfaceAreaKm2 = 377975
                        },
                        new
                        {
                            Id = "86",
                            Capital = "Amman",
                            Currency = "Jordanian Dinar",
                            Name = "Jordan",
                            PopulationMln = 10.1f,
                            President = "Abdullah II bin Al-Hussein",
                            SurfaceAreaKm2 = 89342
                        },
                        new
                        {
                            Id = "87",
                            Capital = "Nur-Sultan",
                            Currency = "Kazakhstani Tenge",
                            Name = "Kazakhstan",
                            PopulationMln = 18.8f,
                            President = "Kassym-Jomart Tokayev",
                            SurfaceAreaKm2 = 2724900
                        },
                        new
                        {
                            Id = "88",
                            Capital = "Nairobi",
                            Currency = "Kenyan Shilling",
                            Name = "Kenya",
                            PopulationMln = 54f,
                            President = "Uhuru Kenyatta",
                            SurfaceAreaKm2 = 580367
                        },
                        new
                        {
                            Id = "89",
                            Capital = "Tarawa Atoll",
                            Currency = "Australian Dollar",
                            Name = "Kiribati",
                            PopulationMln = 0.1f,
                            President = "Taneti Maamau",
                            SurfaceAreaKm2 = 811
                        },
                        new
                        {
                            Id = "90",
                            Capital = "Pristina",
                            Currency = "Euro",
                            Name = "Kosovo",
                            PopulationMln = 1.8f,
                            President = "Vjosa Osmani",
                            SurfaceAreaKm2 = 10908
                        },
                        new
                        {
                            Id = "91",
                            Capital = "Kuwait City",
                            Currency = "Kuwaiti Dinar",
                            Name = "Kuwait",
                            PopulationMln = 4.3f,
                            President = "Jaber Al-Ahmad Al-Sabah",
                            SurfaceAreaKm2 = 17818
                        },
                        new
                        {
                            Id = "92",
                            Capital = "Bishkek",
                            Currency = "Kyrgyzstani Som",
                            Name = "Kyrgyzstan",
                            PopulationMln = 6.7f,
                            President = "Sadyr Japarov",
                            SurfaceAreaKm2 = 199951
                        },
                        new
                        {
                            Id = "93",
                            Capital = "Vientiane",
                            Currency = "Lao Kip",
                            Name = "Laos",
                            PopulationMln = 7.4f,
                            President = "Thongloun Sisoulith",
                            SurfaceAreaKm2 = 236800
                        },
                        new
                        {
                            Id = "94",
                            Capital = "Riga",
                            Currency = "Euro",
                            Name = "Latvia",
                            PopulationMln = 1.9f,
                            President = "Egils Levits",
                            SurfaceAreaKm2 = 64589
                        },
                        new
                        {
                            Id = "95",
                            Capital = "Beirut",
                            Currency = "Lebanese Pound",
                            Name = "Lebanon",
                            PopulationMln = 6.8f,
                            President = "Michel Aoun",
                            SurfaceAreaKm2 = 10452
                        },
                        new
                        {
                            Id = "96",
                            Capital = "Maseru",
                            Currency = "Lesotho Loti",
                            Name = "Lesotho",
                            PopulationMln = 2.1f,
                            President = "Moeketsi Majoro",
                            SurfaceAreaKm2 = 30355
                        },
                        new
                        {
                            Id = "97",
                            Capital = "Monrovia",
                            Currency = "Liberian Dollar",
                            Name = "Liberia",
                            PopulationMln = 5.1f,
                            President = "George Weah",
                            SurfaceAreaKm2 = 111369
                        },
                        new
                        {
                            Id = "98",
                            Capital = "Tripoli",
                            Currency = "Libyan Dinar",
                            Name = "Libya",
                            PopulationMln = 6.7f,
                            President = "Abdul Hamid Dbeibeh",
                            SurfaceAreaKm2 = 1759540
                        },
                        new
                        {
                            Id = "99",
                            Capital = "Vaduz",
                            Currency = "Swiss Franc",
                            Name = "Liechtenstein",
                            PopulationMln = 0.04f,
                            President = "Hans-Adam II",
                            SurfaceAreaKm2 = 160
                        },
                        new
                        {
                            Id = "100",
                            Capital = "Vilnius",
                            Currency = "Euro",
                            Name = "Lithuania",
                            PopulationMln = 2.8f,
                            President = "Gitanas NausÄ—da",
                            SurfaceAreaKm2 = 65300
                        },
                        new
                        {
                            Id = "101",
                            Capital = "Luxembourg",
                            Currency = "Euro",
                            Name = "Luxembourg",
                            PopulationMln = 0.6f,
                            President = "Grand Duke Henri",
                            SurfaceAreaKm2 = 2586
                        },
                        new
                        {
                            Id = "102",
                            Capital = " Antananarivo",
                            Currency = "Malagasy Ariary",
                            Name = "Madagascar",
                            PopulationMln = 27.4f,
                            President = "Andry Rajoelina",
                            SurfaceAreaKm2 = 587041
                        },
                        new
                        {
                            Id = "103",
                            Capital = "Lilongwe",
                            Currency = "Malawian Kwacha",
                            Name = "Malawi",
                            PopulationMln = 19.1f,
                            President = "Lazarus Chakwera",
                            SurfaceAreaKm2 = 118484
                        },
                        new
                        {
                            Id = "104",
                            Capital = "Kuala Lumpur",
                            Currency = "Malaysian Ringgit",
                            Name = "Malaysia",
                            PopulationMln = 32.4f,
                            President = "Abdul Hamid Bador",
                            SurfaceAreaKm2 = 330803
                        },
                        new
                        {
                            Id = "105",
                            Capital = "Male",
                            Currency = "Maldivian Rufiyaa",
                            Name = "Maldives",
                            PopulationMln = 0.5f,
                            President = "Ibrahim Mohamed Solih",
                            SurfaceAreaKm2 = 298
                        },
                        new
                        {
                            Id = "106",
                            Capital = "Bamako",
                            Currency = "West African CFA franc",
                            Name = "Mali",
                            PopulationMln = 20.3f,
                            President = "Bah N'Daw",
                            SurfaceAreaKm2 = 1240192
                        },
                        new
                        {
                            Id = "107",
                            Capital = "Valletta",
                            Currency = "Euro",
                            Name = "Malta",
                            PopulationMln = 0.5f,
                            President = "George Vella",
                            SurfaceAreaKm2 = 316
                        },
                        new
                        {
                            Id = "108",
                            Capital = "Majuro",
                            Currency = "United States Dollar",
                            Name = "Marshall Islands",
                            PopulationMln = 0.06f,
                            President = "David Kabua",
                            SurfaceAreaKm2 = 181
                        },
                        new
                        {
                            Id = "109",
                            Capital = "Nouakchott",
                            Currency = "Mauritanian Ouguiya",
                            Name = "Mauritania",
                            PopulationMln = 4.6f,
                            President = "Mohamed Ould Ghazouani",
                            SurfaceAreaKm2 = 1030700
                        },
                        new
                        {
                            Id = "110",
                            Capital = "Port Louis",
                            Currency = "Mauritian Rupee",
                            Name = "Mauritius",
                            PopulationMln = 1.3f,
                            President = "Prithvirajsing Roopun",
                            SurfaceAreaKm2 = 2040
                        },
                        new
                        {
                            Id = "111",
                            Capital = "Mexico City",
                            Currency = "Mexican Peso",
                            Name = "Mexico",
                            PopulationMln = 126.2f,
                            President = "AndrÃ©s Manuel LÃ³pez Obrador",
                            SurfaceAreaKm2 = 1964375
                        },
                        new
                        {
                            Id = "112",
                            Capital = "Chisinau",
                            Currency = "Moldovan Leu",
                            Name = "Moldova",
                            PopulationMln = 2.6f,
                            President = "Maia Sandu",
                            SurfaceAreaKm2 = 33846
                        },
                        new
                        {
                            Id = "113",
                            Capital = "Monte Carlo",
                            Currency = "Euro",
                            Name = "Monaco",
                            PopulationMln = 0.04f,
                            President = "Albert II of Monaco",
                            SurfaceAreaKm2 = 2
                        },
                        new
                        {
                            Id = "114",
                            Capital = "Ulaanbaatar",
                            Currency = "Mongolian Tugrik",
                            Name = "Mongolia",
                            PopulationMln = 3.3f,
                            President = "Khaltmaagiin Battulga",
                            SurfaceAreaKm2 = 1564116
                        },
                        new
                        {
                            Id = "115",
                            Capital = "Podgorica",
                            Currency = "Euro",
                            Name = "Montenegro",
                            PopulationMln = 0.6f,
                            President = "Milo ÄukanoviÄ‡",
                            SurfaceAreaKm2 = 13812
                        },
                        new
                        {
                            Id = "116",
                            Capital = "Rabat",
                            Currency = "Moroccan Dirham",
                            Name = "Morocco",
                            PopulationMln = 37.3f,
                            President = "Mohammed VI",
                            SurfaceAreaKm2 = 446550
                        },
                        new
                        {
                            Id = "117",
                            Capital = "Maputo",
                            Currency = "Mozambican Met",
                            Name = "Mozambique",
                            PopulationMln = 31.4f,
                            President = "Philipe Nyusi",
                            SurfaceAreaKm2 = 801590
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
